const data=window.RSH_DATA,state={role:'admin',approved:false,published:false,booking:false,tripStarted:false,completed:false,selected:null};
const content=document.querySelector('#content'),title=document.querySelector('#page-title'),label=document.querySelector('#role-label'),message=document.querySelector('#message'),dialog=document.querySelector('#booking-dialog'),form=document.querySelector('#booking-form');
const names={admin:'Admin',company:'Nhà xe',passenger:'Hành khách',driver:'Tài xế'};
function notify(text){message.textContent=text;message.hidden=false;setTimeout(()=>message.hidden=true,3500)}
function button(text,action,kind='primary'){return `<button class="${kind}" data-action="${action}">${text}</button>`}
function render(){label.textContent=names[state.role];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.role===state.role));({admin:adminView,company:companyView,passenger:passengerView,driver:driverView}[state.role])();content.focus()}
function adminView(){title.textContent='Duyệt đăng ký nhà xe';content.innerHTML=`<article class="panel"><div class="row"><div><span class="tag ${state.approved?'success':'warning'}">${state.approved?'APPROVED':'PENDING'}</span><h2>${data.company.name}</h2><p>Đại diện: Nguyễn Văn An · Đà Nẵng</p></div>${state.approved?'<b>Đã phê duyệt</b>':button('Phê duyệt','approve')}</div></article>`}
function companyView(){title.textContent='Chuẩn bị và xuất bản chuyến';content.innerHTML=`<div class="cards"><article class="card"><p class="metric">${data.resources.vehicles}</p><b>Phương tiện</b></article><article class="card"><p class="metric">${data.resources.drivers}</p><b>Tài xế</b></article><article class="card"><p class="metric">${data.resources.routes}</p><b>Tuyến</b></article></div><article class="panel" style="margin-top:16px"><span class="tag ${state.published?'success':'warning'}">${state.published?'PUBLISHED':'DRAFT'}</span><h2>Đà Nẵng → Huế · 07:00</h2><p>Ford Tourneo · Driver A · 6 ghế · 150.000đ</p>${state.approved?(state.published?'<b>Chuyến đang hiển thị cho hành khách</b>':button('Xuất bản chuyến','publish')):'<p class="error">Nhà xe chưa được Admin phê duyệt nên không thể xuất bản.</p>'}</article>`}
function passengerView(){title.textContent=state.booking?'Theo dõi chuyến đã đặt':'Tìm và so sánh chuyến';if(state.booking){content.innerHTML=`<article class="panel"><span class="tag ${state.completed?'success':'warning'}">${state.completed?'COMPLETED':state.tripStarted?'IN_PROGRESS':'BOOKED'}</span><h2>Hải Vân Express · 07:00</h2><p>Hải Châu → Trung tâm Huế</p><div class="facts"><b>${state.tripStarted?'● Vị trí mới nhất: QL1A, Liên Chiểu':'Đang chờ chuyến bắt đầu'}</b><span>Điểm tiếp theo: ${nextStop()}</span></div>${state.completed?`<hr><h3>Đánh giá chuyến đi</h3><div class="stars" aria-label="Chọn đánh giá">${[1,2,3,4,5].map(n=>`<button data-action="rate" data-rating="${n}" aria-label="${n} sao">★</button>`).join('')}</div>`:''}</article>`;return}content.innerHTML=`<form class="panel toolbar" id="search-form"><label>Điểm đi<input value="Đà Nẵng" required></label><label>Điểm đến<input value="Huế" required></label><label>Ngày đi<input type="date" value="2026-10-20" required></label><button class="primary">Tìm chuyến</button></form><div class="cards">${data.trips.map(t=>`<article class="card"><small>${t.company} · ★ ${t.rating}</small><h2>${t.time}</h2><p>${t.vehicle} · còn ${t.seats} ghế</p><p class="price">${t.fare}</p>${button('Chọn chuyến','book','primary').replace('data-action','data-trip="'+t.id+'" data-action')}</article>`).join('')}</div>`}
function driverView(){title.textContent='Thực hiện chuyến được giao';if(!state.booking){content.innerHTML='<div class="panel empty"><h2>Chưa có booking trong demo</h2><p>Chuyển sang Hành khách và tạo booking để sinh danh sách điểm dừng.</p></div>';return}content.innerHTML=`<article class="panel"><div class="row"><div><span class="tag ${state.completed?'success':'warning'}">${state.completed?'COMPLETED':state.tripStarted?'IN_PROGRESS':'ASSIGNED'}</span><h2>Đà Nẵng → Huế · 07:00</h2></div>${!state.tripStarted?button('Nhận và bắt đầu chuyến','start'):''}</div></article><div class="list" style="margin-top:14px">${data.stops.map((s,i)=>`<article class="card stop ${s.done?'done':''}"><div class="row"><div><small>Điểm ${i+1} · ${s.type}</small><h3>${s.name}</h3></div>${state.tripStarted&&!s.done&&i===data.stops.findIndex(x=>!x.done)?button('Hoàn tất điểm','stop','secondary').replace('data-action','data-index="'+i+'" data-action'):s.done?'<b>✓ Hoàn tất</b>':''}</div></article>`).join('')}</div>`}
function nextStop(){const s=data.stops.find(x=>!x.done);return s?s.name:'Không còn điểm dừng'}
document.querySelector('nav').addEventListener('click',e=>{if(e.target.dataset.role){state.role=e.target.dataset.role;render()}});
content.addEventListener('submit',e=>{e.preventDefault();notify('Đã tìm thấy 3 chuyến phù hợp')});
content.addEventListener('click',e=>{const a=e.target.dataset.action;if(!a)return;if(a==='approve'){state.approved=true;notify('Nhà xe đã được phê duyệt')}if(a==='publish'){state.published=true;notify('Chuyến đã được xuất bản')}if(a==='book'){state.selected=data.trips.find(t=>t.id===Number(e.target.dataset.trip));document.querySelector('#booking-title').textContent=`${state.selected.company} · ${state.selected.time}`;dialog.showModal()}if(a==='start'){state.tripStarted=true;notify('Chuyến đã bắt đầu')}if(a==='stop'){data.stops[Number(e.target.dataset.index)].done=true;if(data.stops.every(s=>s.done)){state.completed=true;notify('Mọi điểm dừng đã hoàn tất')}else notify('Đã hoàn tất điểm dừng')}if(a==='rate')notify(`Đã ghi nhận ${e.target.dataset.rating} sao trong mock state`);render()});
form.addEventListener('submit',e=>{e.preventDefault();const seats=Number(document.querySelector('#seats').value),err=document.querySelector('#booking-error');if(seats>state.selected.seats){err.textContent=`Chỉ còn ${state.selected.seats} ghế. Hãy giảm số ghế và thử lại.`;return}if(seats<1){err.textContent='Số ghế phải lớn hơn 0.';return}err.textContent='';state.booking=true;dialog.close();notify('Đã tạo yêu cầu booking; chính sách xác nhận đang chờ quyết định');render()});
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
render();
